export const MOCK_PRODUCTS = [
  {
    id: '1',
    title: 'Laptop Gaming Pro',
    description: 'Laptop de alto rendimiento con RTX 4060, 16GB RAM y SSD 1TB para gaming profesional.',
    price: 4500000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Laptop+Gaming',
    categoryId: 'electronics',
    categoryName: 'Electrónica',
    stock: 12,
    isActive: true,
  },
  {
    id: '2',
    title: 'Smartphone X12',
    description: 'Teléfono inteligente con cámara de 108MP, batería de 5000mAh y pantalla AMOLED 120Hz.',
    price: 2800000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Smartphone+X12',
    categoryId: 'electronics',
    categoryName: 'Electrónica',
    stock: 20,
    isActive: true,
  },
  {
    id: '3',
    title: 'Auriculares Bluetooth Elite',
    description: 'Auriculares inalámbricos con cancelación de ruido activa y 30 horas de autonomía.',
    price: 450000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Auriculares+Elite',
    categoryId: 'electronics',
    categoryName: 'Electrónica',
    stock: 35,
    isActive: true,
  },
  {
    id: '4',
    title: 'Monitor UltraWide 34"',
    description: 'Monitor curvo ultra-wide 34 pulgadas, resolución 3440x1440, 144Hz para productividad y gaming.',
    price: 2100000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Monitor+UltraWide',
    categoryId: 'electronics',
    categoryName: 'Electrónica',
    stock: 8,
    isActive: true,
  },
  {
    id: '5',
    title: 'Camiseta Deportiva DryFit',
    description: 'Camiseta técnica de secado rápido, ideal para entrenamientos intensos y actividades outdoor.',
    price: 85000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Camiseta+DryFit',
    categoryId: 'fashion',
    categoryName: 'Moda',
    stock: 50,
    isActive: true,
  },
  {
    id: '6',
    title: 'Zapatillas Running Air',
    description: 'Zapatillas de running con amortiguación de aire, suela antideslizante y diseño ergonómico.',
    price: 320000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Zapatillas+Running',
    categoryId: 'fashion',
    categoryName: 'Moda',
    stock: 30,
    isActive: true,
  },
  {
    id: '7',
    title: 'Chaqueta Impermeable Trek',
    description: 'Chaqueta cortavientos e impermeable con capucha plegable, perfecta para excursiones.',
    price: 280000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Chaqueta+Trek',
    categoryId: 'fashion',
    categoryName: 'Moda',
    stock: 18,
    isActive: true,
  },
  {
    id: '8',
    title: 'Reloj Inteligente FitLife',
    description: 'Smartwatch con monitoreo de ritmo cardíaco, oxígeno en sangre y notificaciones.',
    price: 520000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Reloj+FitLife',
    categoryId: 'fashion',
    categoryName: 'Moda',
    stock: 25,
    isActive: true,
  },
  {
    id: '9',
    title: 'Lámpara LED Minimalista',
    description: 'Lámpara de escritorio con luz LED regulable, control táctil y puerto de carga USB.',
    price: 120000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Lampara+LED',
    categoryId: 'home',
    categoryName: 'Hogar',
    stock: 40,
    isActive: true,
  },
  {
    id: '10',
    title: 'Silla Ergonómica Office',
    description: 'Silla de oficina con soporte lumbar ajustable, reposabrazos 4D y respaldo de malla.',
    price: 890000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Silla+Ergonomica',
    categoryId: 'home',
    categoryName: 'Hogar',
    stock: 15,
    isActive: true,
  },
  {
    id: '11',
    title: 'Cafetera Espresso Automática',
    description: 'Máquina de café espresso con molino integrado, presión de 15 bares y control digital.',
    price: 1650000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Cafetera+Espresso',
    categoryId: 'home',
    categoryName: 'Hogar',
    stock: 10,
    isActive: true,
  },
  {
    id: '12',
    title: 'Set de Ollas Antiadherentes',
    description: 'Batería de cocina de 5 piezas con revestimiento cerámico, aptas para inducción.',
    price: 380000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Set+Ollas',
    categoryId: 'home',
    categoryName: 'Hogar',
    stock: 22,
    isActive: true,
  },
  {
    id: '13',
    title: 'Mancuernas Ajustables 20kg',
    description: 'Par de mancuernas con peso ajustable de 2kg a 20kg, sistema de bloqueo rápido.',
    price: 420000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Mancuernas+20kg',
    categoryId: 'sports',
    categoryName: 'Deportes',
    stock: 16,
    isActive: true,
  },
  {
    id: '14',
    title: 'Bicicleta MTB Carbono',
    description: 'Bicicleta de montaña con cuadro de carbono, suspensión delantera y 21 velocidades.',
    price: 3200000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Bicicleta+MTB',
    categoryId: 'sports',
    categoryName: 'Deportes',
    stock: 5,
    isActive: true,
  },
  {
    id: '15',
    title: 'Colchoneta Yoga Premium',
    description: 'Mat de yoga antideslizante, espesor 6mm, material ecológico con correa de transporte.',
    price: 95000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Colchoneta+Yoga',
    categoryId: 'sports',
    categoryName: 'Deportes',
    stock: 45,
    isActive: true,
  },
  {
    id: '16',
    title: 'Balón Fútbol Profesional',
    description: 'Balón de fútbol oficial tamaño 5, costuras térmicas y material resistente al agua.',
    price: 135000,
    imageUrl: 'https://via.placeholder.com/600x400?text=Balon+Futbol',
    categoryId: 'sports',
    categoryName: 'Deportes',
    stock: 60,
    isActive: true,
  },
]
